FROM golang:1.11.0
RUN mkdir -p /go/src/github.com/helm
ADD chartmuseum /go/src/github.com/helm/chartmuseum
WORKDIR /go/src/github.com/helm/chartmuseum
RUN ls -la && \
    make clean bootstrap setup-test-environment
